language: java

dist: trusty

jdk:
- openjdk8
#- openjdk9
#- openjdk10
#- oraclejdk8
#- oraclejdk9
#- oraclejdk10

install: /bin/true

branches:
  only:
  - master

env:
- JAVA_TOOL_OPTIONS="-Xmx2g"

script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version
- mvn test verify --batch-mode

after_success:
- mvn javadoc:javadoc
- cd target/site/apidocs/
- git init
- git config user.name "Travis CI"
- git config user.email "github@travis-ci.org"
- git add .
- git commit -m "Deploy to GitHub Pages"
- git push --force "https://${GH_TOKEN}@github.com/ILLGrenoble/preql.git" master:gh-pages > /dev/null 2>&1